train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./datasets/div2k/DIV2K_train_HR
      repeat: 8
      cache: in_memory
  wrapper:
    name: sr-cut-downsampled
    args:
      inp_size: 512
      augment: true
      norm: true
  batch_size: 16

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./datasets/div2k/DIV2K_valid_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-cut-downsampled
    args:
      inp_size: 512
      augment: true
      norm: true
  batch_size: 16


model:
  name: fourierSR-net
  args:
    input_size: 512
    max_freq: 2
    srnet_spec:
      name: rdn
      args:
        G0: 72
        no_upsampling: true

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 100
